### ISSUE TITLE
RuntimeError: no event-loop in thread ‘threading-1

### ISSUE THREAD

**Issue by arian4** [Alimobasheri/covid19-pyweb#11]
Every time after opening the serving page 127.0.0.1:5000 jinja2 returns error RuntimeError: no event-loop in thread ‘Threading-1’.
The program runs finely and there’s no problem with python serving the request. Only after opening the webpage I encounter this error

**Comment by Alimobasheri** [comment]
It’s strange. I think it might be a problem with the asyncio module.
What’s your python version?

**Comment by arian4** [comment]
I’m using python 3.8.2

**Comment by Alimobasheri** [comment]
I will try to solve it ASAP

**Comment by Alimobasheri** [comment]
The bug was repaired thanks to @arian4
